// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBikJaf7uSyCdRBjMo3bvE67-lBJlbcckI',
    appId: '1:666339878022:web:26e56127f5953e82511d07',
    messagingSenderId: '666339878022',
    projectId: 'attendence-ab2bc',
    authDomain: 'attendence-ab2bc.firebaseapp.com',
    storageBucket: 'attendence-ab2bc.appspot.com',
    measurementId: 'G-J4M1T5YL4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQAmn31JPO7OMqNyM1mVM2uSp9nH6SNF8',
    appId: '1:666339878022:android:d7dc801883564b3a511d07',
    messagingSenderId: '666339878022',
    projectId: 'attendence-ab2bc',
    storageBucket: 'attendence-ab2bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgsOlJj5yFgskwLgk99Oo1PFKLJvrTRME',
    appId: '1:666339878022:ios:2c787843d48cf1e5511d07',
    messagingSenderId: '666339878022',
    projectId: 'attendence-ab2bc',
    storageBucket: 'attendence-ab2bc.appspot.com',
    iosClientId: '666339878022-o0dmii5phc1g5sjrcnfje3fgm52907s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgsOlJj5yFgskwLgk99Oo1PFKLJvrTRME',
    appId: '1:666339878022:ios:558f37807b15f84e511d07',
    messagingSenderId: '666339878022',
    projectId: 'attendence-ab2bc',
    storageBucket: 'attendence-ab2bc.appspot.com',
    iosClientId: '666339878022-p2g9mnao21d2v7odn6qvlhvmfjookglf.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendence.RunnerTests',
  );
}
